### ISSUE TITLE
Incomplete information about code

### ISSUE THREAD

**Issue by zhuzhuzhuxin** [hendrycks/fooling#1]
In adversarial_whitening.ipynb:
u_tiny = np.load('./tiny-imagenet/u.npy')
v_tiny = np.load('./tiny-imagenet/v.npy')
have such errors:
FileNotFoundError: [Errno 2] No such file or directory: './tiny-imagenet/u.npy'
FileNotFoundError: [Errno 2] No such file or directory: './tiny-imagenet/v.npy'
but in 'tiny-imagenet', there is no 'u.npy' and 'v.npy'.
Looking forward to your reply as soon as possible.

**Comment by hendrycks** [comment]
I still have u.npy. It didn't get uploaded to github because it is around 0.5 GB.
Here is u.npy:
https://drive.google.com/file/d/1E8NHxHSolw1SVSo70G39tfqtnxvx3JOR/view?usp=sharing

**Comment by zhuzhuzhuxin** [comment]
@hendrycks Thank you for your reply. But I still have no data named 'v.npy'. Could you please send the 'v.npy' to me?

**Comment by hendrycks** [comment]
The code can be run without v.npy. Consider commenting that line since further computation uses u.npy not v.npy. I do not have v.npy anymore.

**Comment by zhuzhuzhuxin** [comment]
@hendrycks Thank you very much! I get it.

**Comment by zhuzhuzhuxin** [comment]
@hendrycks 
When I run this code:
u_tiny = np.load('./tiny-imagenet/u.npy')
I have the error like this:
OSError: Failed to interpret file './tiny-imagenet/u.npy' as a pickle

**Comment by hendrycks** [comment]
I'm not sure the cause, since I have not had that issue. It looks like there are some StackOverflow responses to that error.

**Comment by zhuzhuzhuxin** [comment]
@hendrycks Thank you very much. I have successfully run this program.

**Comment by Hskye** [comment]
Thank you very much.

**Comment by Hskye** [comment]
Hello, can I know how you get the u.npy and s.npy, just like the code using in CIFAR and MNIST? Have you ever met the value in s.npy is very small, and is the code fit for the ImageNet set?

**Comment by hendrycks** [comment]
I am not sure I understand the question. Computing the Principal Components for ImageNet would likely require using a distributed SVD algorithm.
