### ISSUE TITLE
some puzzle about the data provided

### ISSUE THREAD

**Issue by Hskye** [hendrycks/fooling#3]
u.npy and s.npy are provided directly without code? I have some question about these data, I use np.linalg.svd to get s.npy from cifar data, and get the last ones is n*e-6, but ./tinyimagenet/s.npy provided directly are all over e-2. Can you teach me how to get it, thank you very much

**Comment by hendrycks** [comment]
[This site](http://cs231n.github.io/neural-networks-2/) gives a tutorial on computing the Principal Components for CIFAR-10. It's possible the size eigenvalues differ between datasets. Computing the Principal Components on Tiny ImageNet can be done in the same was as with CIFAR, but one needs a computer with lots of RAM and computing the Principal Components takes around an hour.

**Comment by Hskye** [comment]
thank you very much
